- name: Add EPEL repository
  yum:
    name: epel-release
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2.7

- name: Install basic packages
  package:
    name: ['vim','bash-completion','tmux','tree','htop','wget','unzip','curl','git']
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2.7

- name: Install Java 8 CentOS
  yum:
    name: java-1.8.0-openjdk
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2.7

- name: Add "{{ remote_user }}"  group
  group:
    name: "{{ remote_user }}"

- name: Add "{{ remote_user }}" user
  user:
    name: "{{ remote_user }}"
    group: "{{ remote_user }}"
    home: "{{ tomcat_dir }}"
    createhome: no
    system: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Create a tomcat directory
  file:
    path: "{{ tomcat_dir }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: "{{ tomcat_dir }}"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: "{{ tomcat_dir }}/bin"

- name: Copy tomcat variable file setenv.sh
  template:
    src: templates/setenv.sh
    dest: "{{ tomcat_dir }}/bin/setenv.sh"

- name: Copy server.xml
  template:
    src: templates/server.xml
    dest: "{{ tomcat_dir }}/conf/server.xml"

- name: Set UI access credentials
  template:
    src: templates/tomcat-users.xml.j2
    dest: "{{ tomcat_dir }}/conf/tomcat-users.xml"

- name: Allow access to Manager and Host Manager apps from any IP
  template:
    src: templates/context.xml.j2
    dest: "{{ item }}"
  with_items:
    - "{{ tomcat_dir }}/webapps/host-manager/META-INF/context.xml"
    - "{{ tomcat_dir }}/webapps/manager/META-INF/context.xml"

- name: Tomcat start
  shell: nohup "{{ tomcat_dir }}/bin/startup.sh"

- name: wait for port 8080
  wait_for:
    port: 8080
    delay: 20
